# Generated by Django 6.1.2 on 2026-10-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
