# Generated by Django 6.1.1 on 2026-10-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='SEO friendly URL slug', max_length=200, unique=True)),
                ('meta_description', models.CharField(help_text='Google meta description (max 160 chars)', max_length=160)),
                ('content', models.TextField(help_text='Detailed HTML or Markdown content (1500+ words target)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
